
This repository contains C++ code to simulate several epidemiological
models, with emphasis on those most useful to model COVID19.


* Contents

All models mentioned below are implemented in their stochastic
variants.

 - sir :: Simple fully-connected SIR model.  The simplest
   implementation, mostly useful as check for other programs.

 - sir_m :: The same fully-connected SIR as in =sir= but with the
   option to do multiple runs and compute mean and variance across
   realizations of the stochastic dynamcis.

 - sir_f :: A SIR with population divided in families, and different
   in- and out-of-family transmission rates.


* Models

** Simple mean field SIR

The population is composed of \(N\) indistinguishable individuals,
each interacting equally with all the others.  An individual can be in
one of three states S (susceptible), I (infected) or R (recovered).
The dynamics is defined by the transition rates

\[  W^{(i)}_{S\to I} = \beta \frac{N_I}{N-1} \]
\[  W^{(i)}_{I\to R} = \gamma \]




* Building

If you download a release tarball, it's enough to do

: ./configure
: make
: sudo make install

This installs in =/usr/local=, you can give =--prefix= to the
~configure~ script to change this.  The development versions of the
following libraries are required to build, you will get a configure
error if they are missing:

 - GNU Scientific library

** Compile from repository

To compile from a clone of the repository you need to install
=autotools=.  First generate the ~configure~ script with

: autoreconf -if

then proceed with ~configure~ and ~make~ as above.
